export const projects = [
  {
    title: 'AirBnB clone',
    description: "Application web full-stack inspirée d'Airbnb.",
    image: '/images/j3iced6u.bmp',
    tags: ['Java', 'XML', 'Firebase', 'Rest API'],
    source: 'https://github.com/theonlysaad/AirBnB_clone_v4.git',
    visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  {
    title: 'Gestion Employeur',
    description: "Application web développée en .NET (ASP.NET Core) pour la gestion des employés.",
    image: 'images/pou7g9jz.bmp',
    tags: ['.NET Core', 'Entity Framework Core', 'SQL Server', ' Razor Pages'],
    source: 'https://github.com/theonlysaad/GestionEmployer.git',
    visit: 'https://project.vipuljha.com/website/',
    id: 1,
  },
  {
    title: 'Google Maps App',
    description: "Application mobile Flutter reproduisant Google Maps.",
    image: '/images/77nsen32.bmp',
    tags: ['Flutter', 'Google Maps API', 'Dart', 'Android/IOS'],
    source: 'https://github.com/theonlysaad/googlemapsapp.git',
    visit: 'https://forum.xda-developers.com/t/tweak-mod-arm-x86-project-dark-booster-abs-tweaks-v5-0-2-3-6-0-23-01-2016.3120404/',
    id: 2,
  },
  {
    title: 'Gestion Ventes',
    description: "Application de gestion de vente de produits en C# et SQL Server.",
    image: '/images/fyfoprnw.bmp',
    tags: ['C#', 'SQL Server Management Studio', 'Visual Studio'],
    source: 'https://github.com/theonlysaad/GestionVentes.git',
    visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    id: 3,
  },
  {
    title: 'Film APP',
    description: "Application mobile React Native pour consulter les films tendances.",
    image: '/images/6i5pxfbr.bmp',
    tags: ['React Native', 'API TMDB'],
    source: 'https://github.com/theonlysaad/Film-APP.git',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 4,
  },
  {
    title: 'Gestion Bancaire',
    description: "Application web Java EE pour la gestion des comptes bancaires.",
    image: '/images/IBank.png',
    tags: ['Java', 'Jakarta EE', 'Maven', 'MySQL'],
    source: 'https://github.com/theonlysaad/GESTION_BANCAIRE_JPA-main.git',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Début en développement logiciel.' },
  { year: 2017, text: 'Travail intensif sur ROMs & Kernels.' },
  { year: 2018, text: 'Apprentissage du développement Android.' },
  { year: 2019, text: 'Obtention du diplôme en ingénierie informatique.' },
  { year: 2020, text: 'Acquisition de nouvelles compétences en pleine pandémie.' },
  { year: 2021, text: 'Premier emploi chez Primebook.' },
  { year: 2022, text: 'Obtention du B.Tech en IT.' },
  { year: 2023, text: 'Projets et apprentissage en cours...' },
];
